Add clever-frontend submodule and configure web_server
CopterExpress/clever_bundle pull request #3
Opened 2017-11-28 12:24 UTC by urpylka

2017-11-28 18:39 UTC, okalachev requested changes

2017-11-28 18:39 UTC, okalachev commented on .gitmodules
> +[submodule "clever/clever-frontend"]
Там уже переименовали репу.

2017-11-28 18:39 UTC, okalachev commented on README.md
> +Перевести submodule clever-frontend на ветку build
Неудобно каждый раз руками переводить.

2017-11-30 23:36 UTC, okalachev commented
@urpylka, @apostololeg, доделайте пожалуйста.

2017-12-15 14:32 UTC, apostololeg commented
ой, я случайно другой PR сделал https://github.com/CopterExpress/clever_bundle/pull/9

2017-12-15 15:00 UTC, closed without merging