Comment mavros_msgs for build catkin_make
CopterExpress/clever_bundle pull request #4
Opened 2017-11-28 12:28 UTC by urpylka

2017-11-28 18:29 UTC, okalachev commented on clever/CMakeLists.txt
> +  #mavros_msgs
Если это "чинит" сборку, то давай удалять строки, а не комментировать.

2017-11-28 18:32 UTC, okalachev requested changes

2017-11-28 18:32 UTC, okalachev commented on clever/CMakeLists.txt
> +  #mavros_msgs
Если это "чинит" сборку, то давай удалять сроки, а не комментировать.

2017-11-28 21:02 UTC, urpylka commented on clever/CMakeLists.txt
> +  #mavros_msgs
Я не знаю что это чинит, и что это значит. Ты сам понимаешь на что это влияет? Для чего нужна эта строчка и почему вызывает ошибку?

2017-11-28 21:22 UTC, okalachev commented on clever/CMakeLists.txt
> +  #mavros_msgs
Я подключал этот пакет, когда хотел использовать в get_telemetry mavros'овский state. Сейчас я передумал это делать, что он не нужен.

Хотя вообще mavros в зависимостях нужен, но, наверное, как-то не так.

2017-11-29 17:15 UTC, okalachev commented
Убрал эту зависимость.

2017-11-29 17:15 UTC, closed without merging